### ISSUE TITLE
futurecoder and Papyros

### ISSUE THREAD

**Issue by alexmojaki** [amirtds/python_editor_wasm#1]
Hi, I read your article and just wanted to share my work in this space.

I've also created a Pyodide based 'IDE': https://futurecoder.io/course/#ide

It adds enhanced tracebacks, 3 integrated debuggers, a shell, and countless other small improvements.

Another group (cc @winniederidder) is creating Papyros: https://github.com/dodona-edu/papyros

As well as Pyodide, Papyros uses CodeMirror for its editor just like this repo.

futurecoder and Papyros share some underlying code and features because they both use the library https://github.com/alexmojaki/pyodide-worker-runner which provides a better basis for this kind of project than just Pyodide on its own. Papyros itself is an npm package so that it can be customised and integrated into other sites.

**Comment by amirtds** [comment]
Hi @alexmojaki 
Thanks for this detail. This is really great Information. I checked https://futurecoder.io/course/#ide and looks great. I gave it a quick try and liked how you provide feedback to the users based on their interactions in the editor. I would like to learn more about the integrations you have done in the editor.
I will check `Papyros` it sounds interesting. I give it a try and send you my feedback.
Thank you again for your comments

**Comment by alexmojaki** [comment]
> I would like to learn more about the integrations you have done in the editor.

Do you have any specific questions?

**Comment by amirtds** [comment]
Thanks @alexmojaki for your response. I like to learn more about the debugger and also the way you provide feedback to the users. I think https://github.com/alexmojaki/futurecoder is the best starting point for me, and I ask you if I have any specific questions.
