### ISSUE TITLE
Flask

### ISSUE THREAD

**Issue by alexmojaki** [amirtds/python_editor_wasm#2]
Suggesting Flask for this seems like overkill. It's just some static HTML and JS, there's no need for a custom backend. Why not suggest `python -m http.server` for local development, and something like Github Pages for deployment?

**Comment by amirtds** [comment]
Good catch @alexmojaki The version we developed in the article is really basic, but If the users want to they can add more functionality to this, for example handling GET parameters to customizing the editor.
